import type { Locale } from "./i18n";

/**
 * Spec values are stored canonically in English and translated at render time.
 *
 * The alternative — storing a Persian copy per value — would double the facet
 * index and make filter URLs locale-specific, so a link shared between an
 * English-reading engineer and a Persian-reading buyer would break. Canonical
 * storage keeps `?material=Viton` meaningful in both locales.
 */
const FA: Record<string, string> = {
  // --- Elastomers -----------------------------------------------------------
  "Buna-N": "بونا-ان (نیتریل)",
  "Soft Buna-N": "بونا-ان نرم",
  "Hard Buna-N": "بونا-ان سخت",
  Viton: "وایتون (FKM)",
  Silicone: "سیلیکون",
  EPDM: "ای‌پی‌دی‌ام",
  Neoprene: "نئوپرن",
  PTFE: "تفلون (PTFE)",
  Polyurethane: "پلی‌اورتان",
  HNBR: "اچ‌ان‌بی‌آر",
  "Fluorosilicone": "فلوروسیلیکون",
  Nitrile: "نیتریل",
  Rubber: "لاستیک",
  Felt: "نمد",
  Cork: "چوب‌پنبه",
  Leather: "چرم",

  // --- Metals ---------------------------------------------------------------
  "18-8 Stainless Steel": "فولاد زنگ‌نزن ۱۸-۸",
  "316 Stainless Steel": "فولاد زنگ‌نزن ۳۱۶",
  "410 Stainless Steel": "فولاد زنگ‌نزن ۴۱۰",
  "Stainless Steel": "فولاد زنگ‌نزن",
  "Alloy Steel": "فولاد آلیاژی",
  "Carbon Steel": "فولاد کربنی",
  "Zinc-Plated Steel": "فولاد آبکاری روی",
  "Galvanized Steel": "فولاد گالوانیزه",
  "Black-Oxide Steel": "فولاد اکسید سیاه",
  "Low-Carbon Steel": "فولاد کم‌کربن",
  "Tool Steel": "فولاد ابزار",
  "Spring Steel": "فولاد فنر",
  "Cast Iron": "چدن",
  "Ductile Iron": "چدن نشکن",
  Steel: "فولاد",
  Brass: "برنج",
  Bronze: "برنز",
  Copper: "مس",
  Aluminum: "آلومینیوم",
  "6061 Aluminum": "آلومینیوم ۶۰۶۱",
  "7075 Aluminum": "آلومینیوم ۷۰۷۵",
  Titanium: "تیتانیوم",
  "Monel 400": "مونل ۴۰۰",
  "Inconel 600": "اینکونل ۶۰۰",
  Zinc: "روی",

  // --- Plastics -------------------------------------------------------------
  Nylon: "نایلون",
  "Nylon 6/6": "نایلون ۶/۶",
  Acetal: "استال",
  Delrin: "دلرین",
  UHMW: "پلی‌اتیلن فوق سنگین",
  Polypropylene: "پلی‌پروپیلن",
  Polyethylene: "پلی‌اتیلن",
  PVC: "پی‌وی‌سی",
  CPVC: "سی‌پی‌وی‌سی",
  Polycarbonate: "پلی‌کربنات",
  Acrylic: "اکریلیک",
  PEEK: "پیک (PEEK)",
  ABS: "ای‌بی‌اس",
  Fiberglass: "فایبرگلاس",
  Ceramic: "سرامیک",
  Graphite: "گرافیت",

  // --- Finishes -------------------------------------------------------------
  Plain: "بدون پوشش",
  "Zinc Plated": "آبکاری روی",
  "Black Oxide": "اکسید سیاه",
  Passivated: "پسیو شده",
  Anodized: "آنودایز",
  "Hot-Dipped Galvanized": "گالوانیزه گرم",
  "Nickel Plated": "آبکاری نیکل",
  "Chrome Plated": "آبکاری کروم",
  Painted: "رنگ‌شده",
  Polished: "پولیش‌شده",
  Unfinished: "خام",

  // --- Colors ---------------------------------------------------------------
  Black: "مشکی",
  White: "سفید",
  Red: "قرمز",
  Blue: "آبی",
  Green: "سبز",
  Yellow: "زرد",
  Brown: "قهوه‌ای",
  Clear: "شفاف",
  Gray: "خاکستری",
  Orange: "نارنجی",
  Natural: "طبیعی",
  Purple: "بنفش",
  Silver: "نقره‌ای",

  // --- Shapes / types -------------------------------------------------------
  Round: "گرد",
  Square: "مربع",
  Rectangular: "مستطیل",
  Hex: "شش‌گوش",
  Flat: "تخت",
  Oval: "بیضی",
  "X-Profile": "پروفیل ایکس",
  Tapered: "مخروطی",
  Straight: "مستقیم",
  Threaded: "رزوه‌دار",
  Unthreaded: "بدون رزوه",
  Coarse: "درشت",
  Fine: "ریز",
  Metric: "متریک",
  Inch: "اینچی",
  Open: "باز",
  Sealed: "آب‌بندی‌شده",
  Shielded: "درپوش‌دار",
  "Double Sealed": "دو طرف آب‌بندی",
  "Double Shielded": "دو طرف درپوش",
  Left: "چپ‌گرد",
  Right: "راست‌گرد",
  Male: "نری",
  Female: "مادگی",
  "Male x Female": "نری × مادگی",
  "Female x Female": "مادگی × مادگی",
  "Male x Male": "نری × نری",
  NPT: "ان‌پی‌تی",
  BSPT: "بی‌اس‌پی‌تی",
  Flanged: "فلنجی",
  Welded: "جوشی",
  Seamless: "بدون درز",
  Socket: "سوکتی",
  Slotted: "شیاردار",
  Phillips: "چهارسو",
  Torx: "تورکس",
  "Hex Drive": "آلن",
  "External Hex": "شش‌گوش بیرونی",
  Standard: "استاندارد",
  "Heavy Duty": "سنگین",
  "Light Duty": "سبک",
  "Extra Heavy": "فوق سنگین",
  Rigid: "صلب",
  Flexible: "انعطاف‌پذیر",
  Yes: "دارد",
  No: "ندارد",

  // --- Grades / ratings -----------------------------------------------------
  "Grade 2": "گرید ۲",
  "Grade 5": "گرید ۵",
  "Grade 8": "گرید ۸",
  "Class 4.8": "کلاس ۴.۸",
  "Class 8.8": "کلاس ۸.۸",
  "Class 10.9": "کلاس ۱۰.۹",
  "Class 12.9": "کلاس ۱۲.۹",
  "Schedule 40": "رده ۴۰",
  "Schedule 80": "رده ۸۰",
  "Schedule 160": "رده ۱۶۰",
  "150 psi": "۱۵۰ پام",
  "300 psi": "۳۰۰ پام",
  "Durometer 50A (Soft)": "سختی ۵۰A (نرم)",
  "Durometer 70A (Medium)": "سختی ۷۰A (متوسط)",
  "Durometer 75A (Medium)": "سختی ۷۵A (متوسط)",
  "Durometer 90A (Hard)": "سختی ۹۰A (سخت)",
  // --- Descriptive values -----------------------------------------------
  // Standard designations (M12 x 1.75, NEMA 4X, N95, ISO 46, ±0.001") are
  // deliberately absent: they are identifiers, not words, and Iranian buyers
  // match them against manufacturer literature in Latin.
  Light: "سبک",
  Medium: "متوسط",
  Heavy: "سنگین",
  Low: "کم",
  High: "زیاد",
  Single: "تکی",
  Double: "دوتایی",
  "Single Wall": "تک‌لایه",
  "Double Wall": "دولایه",
  Manual: "دستی",
  Automatic: "خودکار",
  Digital: "دیجیتال",
  Dial: "عقربه‌ای",
  Vernier: "ورنیه",
  Mechanical: "مکانیکی",
  Lever: "اهرمی",
  "Locking Lever": "اهرم قفل‌شونده",
  Tee: "دسته T",
  Swing: "لولایی",
  Spring: "فنری",
  Ball: "ساچمه‌ای",
  "Ball End": "سر گرد",
  "Corner Radius": "گوشه گرد",
  Removable: "قابل جدا شدن",
  "Non-Removable": "غیرقابل جدا شدن",
  "One-Piece Clamp": "بست یک‌تکه",
  "Two-Piece Clamp": "بست دوتکه",
  "Set Screw": "پیچ خار",
  Flange: "فلنجی",
  "Pillow Block": "یاتاقان بالشتکی",
  "Take-Up": "کششی",
  "Three-Arm": "سه بازو",
  "Four-Arm": "چهار بازو",
  Knurled: "عاج‌دار",
  Wing: "پروانه‌ای",
  Wall: "دیواری",
  Deck: "روی میز",
  Bottom: "پایین",
  Back: "پشت",
  Hardwood: "چوب سخت",
  Laminate: "لمینت",
  Cardboard: "مقوا",
  "Aluminum Oxide": "اکسید آلومینیوم",
  "Silicon Carbide": "کارباید سیلیکون",
  "Titanium Nitride": "نیترید تیتانیوم",
  Cobalt: "کبالت",
  Uncoated: "بدون پوشش",
  "Hook and Loop": "چسب کِرکی",
  Adhesive: "چسبی",
  "Anti-Fog": "ضد بخار",
  "Scratch-Resistant": "ضد خش",
  "Anti-Fog and Scratch-Resistant": "ضد بخار و ضد خش",
  Wraparound: "دورگیر",
  "Over-Glasses": "روی عینک",
  Amber: "کهربایی",
  Danger: "خطر",
  Warning: "هشدار",
  Caution: "احتیاط",
  Notice: "توجه",
  English: "انگلیسی",
  Persian: "فارسی",
  Bilingual: "دوزبانه",
  Blank: "بدون علامت",
  Assorted: "متنوع",
  Lithium: "لیتیوم",
  "Lithium Complex": "لیتیوم کمپلکس",
  Polyurea: "پلی‌اوره",
  "Calcium Sulfonate": "کلسیم سولفونات",
  "Water-Based": "پایه آب",
  "Solvent-Based": "پایه حلال",
  Citrus: "مرکبات",
  "Stick (SMAW)": "الکترود دستی (SMAW)",
  "MIG (GMAW)": "میگ (GMAW)",
  "TIG (GTAW)": "تیگ (GTAW)",
  "Bent 45°": "خم ۴۵ درجه",
  "Bent 90°": "خم ۹۰ درجه",
  "304 Stainless Steel": "فولاد زنگ‌نزن ۳۰۴",
  "440C Stainless Steel": "فولاد زنگ‌نزن ۴۴۰C",
  "Female x Female x Female": "مادگی × مادگی × مادگی",
  "Male x Female x Female": "نری × مادگی × مادگی",

  "ASTM D2000": "ASTM D2000",
  "AS568": "AS568",
  "DIN 3771": "DIN 3771",
  "Mil. Spec.": "استاندارد نظامی",
  "FDA Compliant": "منطبق با FDA",
  "None": "ندارد",
};

export function specValueLabel(value: string, locale: Locale): string {
  if (locale !== "fa") return value;
  return FA[value] ?? value;
}

/** True when the value should render in a forced-LTR cell (dimensions, codes). */
export function isTechnicalValue(v: string | number | null): boolean {
  if (typeof v === "number") return true;
  if (typeof v !== "string") return false;
  // Anything containing Latin digits or an inch mark is a measurement or code.
  return /[0-9]/.test(v) && !/[؀-ۿ]/.test(v);
}
